### ISSUE TITLE
Error 404 What happened?

### ISSUE THREAD

**Issue by DambronOlivier** [ladybug-tools/spider-2022#1]
hi @theo-armour 

Error 404 What happened?

**Comment by theo-armour** [comment]
@DambronOlivier 

I just had a quick look. It seems okay to me. Not yet much to show. I'm currently working on new camera paths generated by algorithm.

Can you send me the link you tried?

**Comment by DambronOlivier** [comment]
this one https://ladybug.tools/spider-2022/spider-viewer/

"new camera paths generated by algorithm" sounds super interesting!

**Comment by DavidHollman** [comment]
Its the "Full Screen" link right from https://github.com/ladybug-tools/spider-2022 which is broken.

**Comment by mostaphaRoudsari** [comment]
I can also confirm that it is broken. It might be because @theo-armour has moved or renamed the folder.

**Comment by theo-armour** [comment]
I will look at the issue this evening. Thank you for reporting the error!

**Comment by theo-armour** [comment]
@DambronOlivier 

Sorry for the slowness. Please try again!

https://www.ladybug.tools/spider-2022/spider-viewer/

![image](https://user-images.githubusercontent.com/547626/195954591-77e9534a-a361-4ad2-9ea9-b10e6141ea06.png)

**Comment by mostaphaRoudsari** [comment]
It works! Thank you, @theo-armour!
